# Broker del VPS. Sin listener sin cifrar y sin acceso anónimo.

persistence true
persistence_location /mosquitto/data/
log_dest stdout

listener 8883
protocol mqtt
cafile   /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile  /mosquitto/certs/server.key
tls_version tlsv1.2

allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl

max_keepalive 120
